package OJ;

public class Test {
    public static void main(String[] args) {
        String str="asfafafasfafhuehfguhwhfgqh0fhioahfiahcihasfafafasfafhuehfguhwhfgqh0fhioahfiahcihjaichnciahifhihfgiqehgtyrwigohiohgviaipojfipoawjfpiojojpoqjfpoqajfgpjfpoiejgpojepogjopajvoajvlamvpejgjiqhjjopfjepofgjeopjgsgsgegegasfafafasfafhuehfguhwhfgqh0fhioahfiahcihjaichnciahifhihfgiqehgtyrwigohiohgviaipojfipoawjfpiojojpoqjfpoqajfgpjfpoiejgpojepogjopajvoajvlamvpejgjiqhjjopfjepofgjeopjesdgfegswgwsrghasfafafasfafhuehfguhwhfgqh0fhioahfiahcihjaichnciahifhihfgiqehgtyrwigohiohgviaipojfipoawjfpiojojpoqjfpoqajfgpjfpoiejgpojepogjopajvoajvlamvpejgjiqhjjopfjepofgjeopjsegegwegasfafafasfafhuehfguhwhfgqh0fhioahfiahcihjaichnciahifhihfgiqehgtyrwigohiohgviaipojfipoawjfpiojojpoqjfpoqajfgpjfpoiejgpojepogjopajvoajvlamvpejgjiqhjjopfjepofgjeopjasfafafasfafhuehfguhwhfgqh0fgasegashioahfiahcihjaichnciahifhihfgiqehgtyrwigohiohgviaipojfipoawjfpiojojpoqjfpoqajfgpjfpoiejgpojepogjopajvoajvlamvpejgjiqhjjopfjepofgjeopjasfafafasfafhuehfguhwhfgqh0fhioahfiahcihjaichnciahifhihfgiqehgtyrwigohiohgviaipojfipoawjfpiojojpoqjfpoqajfgpjfpoiejgpojepogjopajvoajvlamvpejgjiqhjjopfjepofgjeopjasfafafasfafhuehfguhwhfgqh0fhioahfiahcihjaichnciahifhihfgiqehgtyrwigohiohgviaipojfipoawjfpiojojpoqjfpoqajfgpjfpoiejgpojepogjopajvoajvlamvpejgjiqhjjopfjepofgjeopjasfafafasfafhuehfguhwhfgqh0fhioahfiahcihjaichnciahifhihfgiqehgtyrwigohiohgviaipojfipoawjfpiojojp";
        System.out.println(str.length());
    }
}
